package com.curseclient.client.utility.render.font.impl


object BonIcon {
    //SpotifyStatus
    var PREVIOUS = "!"
    var NEXT = "\""
    var PLAY = "2"
    var PAUSE = "4"
    var REPEAT = "5"
    var REPEAT_ON = "6"
    var REPEAT_ON_ONE = "7"
    var SHUFFLE = "8"
    var SHUFFLE_ON = "9"
    var CHECKBOX_LINE_BLANK = "a"
    var ADD = "b"
    var ADD_CIRCLE = "c"
    var ADD_BOX = "d"
    var CHECK = "e"
    var CHECK_CIRCLE = "f"
    var CHECK_BOX = "g"
    var CLOSE = "h"
    var CANCEL = "i"
    var DISABLE_DEFAULT = "j"
    var DELETE = "k"
    var FAVORITE = "l"
    var DOWNLOAD = "m"
    var PERSON = "n"
    var GROUP = "o"
    var GROUPS = "p"
    var PUBLIC = "q"
    var OPEN_NEW = "r"
    var POWER = "s"
    var REFRESH = "t"
    var SETTINGS = "u"
    var VISIBILITY = "v"
    var WARNING = "w"
    var INFO = "x"
    var LEFT_MOUSE = "y"
    var RIGHT_MOUSE = "z"
    var SWORDS = "A"
    var HOME = "B"
    var STAR = "C"
    var BOLT = "D"
    var RUN = "E"
    var WALK = "F"
    var Transfer_Within_Station = "G"
    var LIST_ALT = "H"
    var LIST = "I"
    var REORDER = "J"
    var SCREENSHOT = "K"
    var DESKTOP_WINDOWS = "L"
    var TV = "M"
    var APPS = "N"
    var MORE_VERTICAL = "O"

    //public static String ? = "P";
    var TUNE = "Q"
    var ARROW_BACK = "R"
    var ARROW_FORWARD = "S"
    var ARROW_UPWARD = "T"
    var ARROW_DOWNWARD = "U"
    var LOGOUT = "V"
    var LOGIN = "W"
    var EXPAND_LESS = "X"
    var EXPAND_MORE = "Y"
    var CIRCLE = "Z"
}